# Generated by Django 4.1.7 on 2023-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='title_tag',
            field=models.CharField(default='My Blog', max_length=255),
        ),
    ]
