# Generated by Django 4.1.7 on 2023-04-16 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0002_postdata_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='published_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
