# Generated by Django 4.1.7 on 2023-04-24 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypost', '0003_postdata_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='title_tag',
            field=models.IntegerField(default=1, blank=True, null=True),
        ),
    ]
