# Generated by Django 4.1.7 on 2023-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0004_postdata_likes_alter_postdata_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
