# Generated by Django 4.2 on 2023-04-28 09:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0006_category_postdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
