# Generated by Django 4.2 on 2023-04-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0007_alter_postdata_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
