# Generated by Django 4.2 on 2023-04-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0010_profile_facebook_link_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_link',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_link',
            new_name='twitter_url',
        ),
    ]
