# Generated by Django 4.2 on 2023-04-30 09:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0011_rename_facebook_link_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mypost.postdata')),
            ],
        ),
    ]
